posts/urls.py
from django.urls import path
from .views import SudokuListView, SudokuDetailView, HomeView, AboutView


app_name = 'posts'

urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('listall/', SudokuListView.as_view(), name='list'),
    path('detail/<uuid:pk>/', SudokuDetailView.as_view(), name='detail'),
    path('about/', AboutView.as_view(), name='about')
]

sudoku_project/urls.py
from django.contrib import admin
from django.http import Http404, HttpResponse
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.http.response import HttpResponseRedirect
from django.views.static import serve


def index(request, *args, **kwargs):
    return HttpResponseRedirect('sudoku/home/', *args, **kwargs)


# def null(request, *args, **kwargs):
#     return HttpResponse('rESponsee')


# urlpatterns = [re_path(r'.', null)]
urlpatterns = [
    path('',   index),
    path('sudoku/', include('posts.urls', namespace='posts')),
    path('nimda/', admin.site.urls),
    path('account/', include('users.urls', namespace='users')),
    path('account/', include('django.contrib.auth.urls')),
    # re_path(r'static/(?P<path>.*)', serve,
    #         {'document_root': settings.STATIC_ROOT}),
    # ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

]

users/urls.py
from django import template
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import UserLoginForm, PwdResetForm, PwdResetConfirmForm, PwdChangeForm


app_name = 'users'

urlpatterns = [
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name="registration/password_change_form.html",
                                                                   form_class=PwdChangeForm), name='pwdforget'),
    path('login/', auth_views.LoginView.as_view(template_name="registration/login.html",
                                                authentication_form=UserLoginForm), name='login'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name="registration/password_reset_form.html", form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html', form_class=PwdResetConfirmForm),
        name="pwdresetconfirm"),


    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/delete/<uuid:pk>/',
         views.DeleteUserView.as_view(), name='deleteuser'),
    path('register/', views.AccountsRegisterView.as_view(), name='register'),

    path('activate/<slug:uidb64>/<slug:token>/',
         views.ActivateView.as_view(), name='activate'),

]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>

    {% load static %}
    <link rel="stylesheet" href="{% static '/base/style.css' %}" />


    <title>
        title
    </title>
</head>

<body>

    <nav role='navigation'>
        <ul>
            {% if user.is_authenticated %}
            <li><a href="{% url 'posts:home' %}">Home</a></li>
            <li><a id="username" href="{% url 'users:profile' %}">Hi {{user.username}}</a>
                <ul>
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                    <li><a href="{% url 'users:deleteuser' pk=user.id %}">Delete Account</a></li>
                    <li><a href="{% url 'users:pwdforget' %}">Change Password</a></li>
                </ul>
            </li>
            <li><a href="{% url 'posts:list' %}">Other's Posts </a></li>
            <li><a href="{% url 'posts:about' %}">About</a></li>



            {% else %}
            <li><a href="{% url 'posts:home' %}">Home</a></li>
            <li><a href="{% url 'users:login' %}">Sign-In </a></li>
            <li><a href="{% url 'users:register' %}">Sign-Up</a></li>
            <li><a href="{% url 'posts:about' %}">About</a></li>
            {% endif %}
        </ul>
        <a href="{% url 'posts:home' %}" id="name"> Sudoku Vision</a>
    </nav>

    {% block content %}
    {% endblock %}

</body>

</html>

templates/base/footer.html
<div>
    <p>this is footer</p>
</div>